### PR TITLE
Add Cilium v1.9.6

### PR DESCRIPTION
**Pull request by christarazi**
Now that Cilium v1.9.6 has been released, update the manifests.

### CODE REVIEW

**Comment by christarazi** [comment]
cc @errordeveloper

**Comment by errordeveloper** [comment]
Hey @christarazi, I am on leave this week, so only had a quick look. It looks about right overall, was it easy enough to figure what needs doing?

**Comment by errordeveloper** [comment]
Also, after merging there are a few additional steps to do with certification. I'd be keen to work through those with you, and make sure we write down the essential info. I have a bit too much context, so working with someone new to this seems like the best way of documenting it - wdyt?

**Comment by christarazi** [comment]
@errordeveloper I was initially following https://docs.cilium.io/en/latest/gettingstarted/k8s-install-openshift-okd and the step I tripped up on and led to this PR is `Next, obtain Cilium manifest from cilium/cilium-olm repository and copy to ${CLUSTER_NAME}/manifests:`. 

I just got a generic shell error about `/tmp/cilium-olm-${cilium_olm_rev}/manifests/cilium.v1.9.90/*` not existing. Then I went into that directly and realized that all the Cilium released versions are there, i.e. v1.9.5. Since I am trying to validate v1.9.6 for IPSec, I eventually found a script called `add-release.sh` and used it. The script did pretty much everything. It did make some assumpotions about my environment that were wrong such as needing `imagine` in the `PATH`, for which I manually installed using `go install`.

Sure, I'd be happy to work with you on sharing the context and getting it all written down somewhere.

**Comment by christarazi** [comment]
@errordeveloper Actually I tripped up on another part of the docs as well:

```
And set networkType: Cilium:

sed -i 's/networkType:\ OVNKubernetes/networkType:\ Cilium/' "${CLUSTER_NAME}/install-config.yaml"
```

The network type I had in my `install-config.yaml` was `OpenShiftSDN`, so the `sed` was ineffective.  I didn't double-check the output of the `install-config.yaml` and proceeded with the rest of the process. In the end, I was running into strange issues with Cilium not managing any endpoints, but in retrospect, that makes perfect sense why.

**Review by errordeveloper — APPROVED** [review]
All looks good! Other types of updates in this repo can be a bit more nuanced, but adding a release is pretty simple with the script.

**Pull request merged**
